// Code generated by internal/gen from tools.json. DO NOT EDIT.

package server

// CheckServerInput holds the arguments for the check_server tool.
type CheckServerInput struct{}

// RestartServerInput holds the arguments for the restart_server tool.
type RestartServerInput struct{}

// NewCanvasInput holds the arguments for the new_canvas tool.
type NewCanvasInput struct {
	Width      int     `json:"width" jsonschema:"Canvas width in pixels"`
	Height     int     `json:"height" jsonschema:"Canvas height in pixels"`
	Name       *string `json:"name" jsonschema:"Layer/image name (default: \"Untitled\")"`
	ColorMode  *string `json:"color_mode" jsonschema:"\"RGB\" (default), \"RGBA\", \"GRAY\", \"GRAYA\""`
	Fill       *string `json:"fill" jsonschema:"Fill color for the background layer. Any CSS color name or hex string: \"white\" (default), \"black\", \"transparent\", \"#FF5733\", \"rgb(100,200,50)\", etc."`
	Resolution *int    `json:"resolution" jsonschema:"DPI resolution (default: 72)"`
}

// SetDefaults applies the defaults documented for the new_canvas tool.
func (in *NewCanvasInput) SetDefaults() {
	if in.Name == nil {
		in.Name = ptr("Untitled")
	}
	if in.ColorMode == nil {
		in.ColorMode = ptr("RGB")
	}
	if in.Fill == nil {
		in.Fill = ptr("white")
	}
	if in.Resolution == nil {
		in.Resolution = ptr(72)
	}
}

// GetImageBitmapInput holds the arguments for the get_image_bitmap tool.
type GetImageBitmapInput struct {
	MaxWidth  *int           `json:"max_width" jsonschema:"Target dimensions for scaling (aspect-ratio preserved). Omit for full resolution."`
	MaxHeight *int           `json:"max_height" jsonschema:"Target dimensions for scaling (aspect-ratio preserved). Omit for full resolution."`
	Region    map[string]any `json:"region" jsonschema:"Dictionary with keys: - origin_x, origin_y: Top-left corner of region to extract - width, height: Dimensions of region to extract - max_width, max_height: Optional scaling for the extracted region"`
}

// GetImageMetadataInput holds the arguments for the get_image_metadata tool.
type GetImageMetadataInput struct{}

// GetGimpInfoInput holds the arguments for the get_gimp_info tool.
type GetGimpInfoInput struct{}

// GetStateSnapshotInput holds the arguments for the get_state_snapshot tool.
type GetStateSnapshotInput struct {
	ImageIndex int            `json:"image_index" jsonschema:"Which open image to snapshot (default: 0 = most recent)"`
	MaxSize    *int           `json:"max_size" jsonschema:"Maximum width/height of the returned preview in pixels (default: 512)"`
	Region     map[string]any `json:"region" jsonschema:"Optional dict {x, y, width, height} to zoom into a specific area e.g. {\"x\": 200, \"y\": 300, \"width\": 100, \"height\": 80} for mouth area"`
	Label      string         `json:"label" jsonschema:"Optional annotation label (logged but not drawn — for agent bookkeeping)"`
}

// SetDefaults applies the defaults documented for the get_state_snapshot tool.
func (in *GetStateSnapshotInput) SetDefaults() {
	if in.MaxSize == nil {
		in.MaxSize = ptr(512)
	}
}

// GetContextStateInput holds the arguments for the get_context_state tool.
type GetContextStateInput struct{}

// CallAPIInput holds the arguments for the call_api tool.
type CallAPIInput struct {
	APIPath string         `json:"api_path" jsonschema:"The PDB procedure name, e.g. \"gimp-image-get-layers\""`
	Args    []any          `json:"args" jsonschema:"Positional arguments matched in order against the procedure's signature"`
	Kwargs  map[string]any `json:"kwargs" jsonschema:"Arguments by name; preferred over args"`
}

// SetDefaults applies the defaults documented for the call_api tool.
func (in *CallAPIInput) SetDefaults() {
	if in.Args == nil {
		in.Args = []any{}
	}
	if in.Kwargs == nil {
		in.Kwargs = map[string]any{}
	}
}

// DescribeProcedureInput holds the arguments for the describe_procedure tool.
type DescribeProcedureInput struct {
	APIPath string `json:"api_path" jsonschema:"The PDB procedure name, e.g. \"gimp-image-scale\""`
}

// OpenImageInput holds the arguments for the open_image tool.
type OpenImageInput struct {
	FilePath string `json:"file_path" jsonschema:"Absolute path to the image file to open (PNG, JPEG, TIFF, etc.)"`
}

// SaveXcfInput holds the arguments for the save_xcf tool.
type SaveXcfInput struct {
	FilePath   string `json:"file_path" jsonschema:"Absolute path for the output .xcf file"`
	ImageIndex int    `json:"image_index" jsonschema:"Index of the image to save (default 0 = first open image)"`
}

// ExportImageInput holds the arguments for the export_image tool.
type ExportImageInput struct {
	FilePath   string  `json:"file_path" jsonschema:"Absolute path for the output file"`
	Format     *string `json:"format" jsonschema:"Output format — \"png\" (default), \"jpeg\", \"webp\", \"tiff\""`
	Quality    *int    `json:"quality" jsonschema:"JPEG/WEBP quality 1-100 (default 90; ignored for PNG/TIFF)"`
	Flatten    *bool   `json:"flatten" jsonschema:"Flatten all layers before export (default True)"`
	ImageIndex int     `json:"image_index" jsonschema:"Index of the image to export (default 0)"`
}

// SetDefaults applies the defaults documented for the export_image tool.
func (in *ExportImageInput) SetDefaults() {
	if in.Format == nil {
		in.Format = ptr("png")
	}
	if in.Quality == nil {
		in.Quality = ptr(90)
	}
	if in.Flatten == nil {
		in.Flatten = ptr(true)
	}
}

// BatchExportInput holds the arguments for the batch_export tool.
type BatchExportInput struct {
	OutputDir   string  `json:"output_dir" jsonschema:"Directory to write exported files into"`
	Format      *string `json:"format" jsonschema:"\"png\", \"jpeg\", \"webp\", \"tiff\" (default \"png\")"`
	Quality     *int    `json:"quality" jsonschema:"JPEG/WEBP quality (default 90)"`
	NamePattern *string `json:"name_pattern" jsonschema:"Filename template — use {name} for image name, {index} for position"`
	ImageIndex  *int    `json:"image_index" jsonschema:"If set, export only that image; omit to export all open images"`
}

// SetDefaults applies the defaults documented for the batch_export tool.
func (in *BatchExportInput) SetDefaults() {
	if in.Format == nil {
		in.Format = ptr("png")
	}
	if in.Quality == nil {
		in.Quality = ptr(90)
	}
	if in.NamePattern == nil {
		in.NamePattern = ptr("{name}")
	}
}

// AutoLevelsInput holds the arguments for the auto_levels tool.
type AutoLevelsInput struct {
	ImageIndex int     `json:"image_index" jsonschema:"Index of the target image (default 0)"`
	LayerName  *string `json:"layer_name" jsonschema:"Name of the layer to adjust; defaults to active layer"`
}

// AdjustCurvesInput holds the arguments for the adjust_curves tool.
type AdjustCurvesInput struct {
	Preset     *string `json:"preset" jsonschema:"Built-in curve shape — \"s_curve\" (default), \"lighten\", \"darken\", \"contrast\""`
	Points     []any   `json:"points" jsonschema:"Custom control points as [[input, output], ...] override (overrides preset)"`
	Channel    *string `json:"channel" jsonschema:"\"value\" (all), \"red\", \"green\", \"blue\", \"alpha\""`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
	LayerName  *string `json:"layer_name" jsonschema:"Layer to adjust; defaults to active layer"`
}

// SetDefaults applies the defaults documented for the adjust_curves tool.
func (in *AdjustCurvesInput) SetDefaults() {
	if in.Preset == nil {
		in.Preset = ptr("s_curve")
	}
	if in.Channel == nil {
		in.Channel = ptr("value")
	}
}

// AdjustBrightnessContrastInput holds the arguments for the adjust_brightness_contrast tool.
type AdjustBrightnessContrastInput struct {
	Brightness int     `json:"brightness" jsonschema:"-127 to +127 (default 0)"`
	Contrast   int     `json:"contrast" jsonschema:"-127 to +127 (default 0)"`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
	LayerName  *string `json:"layer_name" jsonschema:"Layer to adjust; defaults to active layer"`
}

// AdjustHueSaturationInput holds the arguments for the adjust_hue_saturation tool.
type AdjustHueSaturationInput struct {
	Hue        float64 `json:"hue" jsonschema:"Hue rotation -180 to +180 (default 0)"`
	Saturation float64 `json:"saturation" jsonschema:"Saturation shift -100 to +100 (default 0)"`
	Lightness  float64 `json:"lightness" jsonschema:"Lightness shift -100 to +100 (default 0)"`
	ColorRange *string `json:"color_range" jsonschema:"\"all\", \"red\", \"yellow\", \"green\", \"cyan\", \"blue\", \"magenta\" (default \"all\")"`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
	LayerName  *string `json:"layer_name" jsonschema:"Layer to adjust; defaults to active layer"`
}

// SetDefaults applies the defaults documented for the adjust_hue_saturation tool.
func (in *AdjustHueSaturationInput) SetDefaults() {
	if in.ColorRange == nil {
		in.ColorRange = ptr("all")
	}
}

// AdjustColorBalanceInput holds the arguments for the adjust_color_balance tool.
type AdjustColorBalanceInput struct {
	CyanRed      float64 `json:"cyan_red" jsonschema:"-100 to +100 (negative = cyan, positive = red; default 0)"`
	MagentaGreen float64 `json:"magenta_green" jsonschema:"-100 to +100 (default 0)"`
	YellowBlue   float64 `json:"yellow_blue" jsonschema:"-100 to +100 (default 0)"`
	Range        *string `json:"range" jsonschema:"\"shadows\", \"midtones\" (default), \"highlights\""`
	ImageIndex   int     `json:"image_index" jsonschema:"Target image index (default 0)"`
	LayerName    *string `json:"layer_name" jsonschema:"Layer to adjust; defaults to active layer"`
}

// SetDefaults applies the defaults documented for the adjust_color_balance tool.
func (in *AdjustColorBalanceInput) SetDefaults() {
	if in.Range == nil {
		in.Range = ptr("midtones")
	}
}

// SharpenInput holds the arguments for the sharpen tool.
type SharpenInput struct {
	Amount     *float64 `json:"amount" jsonschema:"Sharpening strength 0-500 (default 50.0)"`
	Radius     *float64 `json:"radius" jsonschema:"Blur radius for the mask in pixels (default 3.0)"`
	Threshold  int      `json:"threshold" jsonschema:"Minimum difference before sharpening is applied (default 0)"`
	ImageIndex int      `json:"image_index" jsonschema:"Target image index (default 0)"`
	LayerName  *string  `json:"layer_name" jsonschema:"Layer to sharpen; defaults to active layer"`
}

// SetDefaults applies the defaults documented for the sharpen tool.
func (in *SharpenInput) SetDefaults() {
	if in.Amount == nil {
		in.Amount = ptr(50.0)
	}
	if in.Radius == nil {
		in.Radius = ptr(3.0)
	}
}

// BlurInput holds the arguments for the blur tool.
type BlurInput struct {
	RadiusX    *float64 `json:"radius_x" jsonschema:"Horizontal blur radius in pixels (default 5.0)"`
	RadiusY    *float64 `json:"radius_y" jsonschema:"Vertical blur radius in pixels (default 5.0)"`
	ImageIndex int      `json:"image_index" jsonschema:"Target image index (default 0)"`
	LayerName  *string  `json:"layer_name" jsonschema:"Layer to blur; defaults to active layer"`
}

// SetDefaults applies the defaults documented for the blur tool.
func (in *BlurInput) SetDefaults() {
	if in.RadiusX == nil {
		in.RadiusX = ptr(5.0)
	}
	if in.RadiusY == nil {
		in.RadiusY = ptr(5.0)
	}
}

// DenoiseInput holds the arguments for the denoise tool.
type DenoiseInput struct {
	Strength   *int    `json:"strength" jsonschema:"Noise reduction strength 0-100 (default 50)"`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
	LayerName  *string `json:"layer_name" jsonschema:"Layer to denoise; defaults to active layer"`
}

// SetDefaults applies the defaults documented for the denoise tool.
func (in *DenoiseInput) SetDefaults() {
	if in.Strength == nil {
		in.Strength = ptr(50)
	}
}

// DesaturateInput holds the arguments for the desaturate tool.
type DesaturateInput struct {
	Mode       *string `json:"mode" jsonschema:"Desaturation algorithm — \"luminosity\" (default), \"luma\", \"average\", \"lightness\""`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
	LayerName  *string `json:"layer_name" jsonschema:"Layer to desaturate; defaults to active layer"`
}

// SetDefaults applies the defaults documented for the desaturate tool.
func (in *DesaturateInput) SetDefaults() {
	if in.Mode == nil {
		in.Mode = ptr("luminosity")
	}
}

// InvertColorsInput holds the arguments for the invert_colors tool.
type InvertColorsInput struct {
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
	LayerName  *string `json:"layer_name" jsonschema:"Layer to invert; defaults to active layer"`
}

// ScaleImageInput holds the arguments for the scale_image tool.
type ScaleImageInput struct {
	Width         int     `json:"width" jsonschema:"Target width in pixels"`
	Height        int     `json:"height" jsonschema:"Target height in pixels"`
	Interpolation *string `json:"interpolation" jsonschema:"\"cubic\" (default), \"linear\", \"none\""`
	ImageIndex    int     `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetDefaults applies the defaults documented for the scale_image tool.
func (in *ScaleImageInput) SetDefaults() {
	if in.Interpolation == nil {
		in.Interpolation = ptr("cubic")
	}
}

// ScaleToFitInput holds the arguments for the scale_to_fit tool.
type ScaleToFitInput struct {
	MaxWidth      int     `json:"max_width" jsonschema:"Maximum allowed width in pixels"`
	MaxHeight     int     `json:"max_height" jsonschema:"Maximum allowed height in pixels"`
	Interpolation *string `json:"interpolation" jsonschema:"\"cubic\" (default), \"linear\", \"none\""`
	ImageIndex    int     `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetDefaults applies the defaults documented for the scale_to_fit tool.
func (in *ScaleToFitInput) SetDefaults() {
	if in.Interpolation == nil {
		in.Interpolation = ptr("cubic")
	}
}

// CropToSelectionInput holds the arguments for the crop_to_selection tool.
type CropToSelectionInput struct {
	Autocrop   bool `json:"autocrop" jsonschema:"If True, auto-detect crop bounds instead of using selection (default False)"`
	ImageIndex int  `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// CropToRectInput holds the arguments for the crop_to_rect tool.
type CropToRectInput struct {
	X          int `json:"x" jsonschema:"Top-left corner of the crop rectangle"`
	Y          int `json:"y" jsonschema:"Top-left corner of the crop rectangle"`
	Width      int `json:"width" jsonschema:"Dimensions of the crop rectangle"`
	Height     int `json:"height" jsonschema:"Dimensions of the crop rectangle"`
	ImageIndex int `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// RotateImageInput holds the arguments for the rotate_image tool.
type RotateImageInput struct {
	Angle      float64 `json:"angle" jsonschema:"Rotation in degrees — 90, 180, 270 use lossless GIMP rotation; other values rotate all layers with interpolation and flatten"`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// FlipImageInput holds the arguments for the flip_image tool.
type FlipImageInput struct {
	Direction  *string `json:"direction" jsonschema:"\"horizontal\" (default) or \"vertical\""`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetDefaults applies the defaults documented for the flip_image tool.
func (in *FlipImageInput) SetDefaults() {
	if in.Direction == nil {
		in.Direction = ptr("horizontal")
	}
}

// ResizeCanvasInput holds the arguments for the resize_canvas tool.
type ResizeCanvasInput struct {
	Width      int     `json:"width" jsonschema:"New canvas dimensions in pixels"`
	Height     int     `json:"height" jsonschema:"New canvas dimensions in pixels"`
	Anchor     *string `json:"anchor" jsonschema:"Position of existing content — \"center\" (default), \"top-left\", \"top\", \"top-right\", \"left\", \"right\", \"bottom-left\", \"bottom\", \"bottom-right\""`
	Fill       *string `json:"fill" jsonschema:"Color for new canvas areas — CSS color or \"transparent\""`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetDefaults applies the defaults documented for the resize_canvas tool.
func (in *ResizeCanvasInput) SetDefaults() {
	if in.Anchor == nil {
		in.Anchor = ptr("center")
	}
	if in.Fill == nil {
		in.Fill = ptr("transparent")
	}
}

// SelectRectangleInput holds the arguments for the select_rectangle tool.
type SelectRectangleInput struct {
	X          int     `json:"x" jsonschema:"Top-left corner of the selection"`
	Y          int     `json:"y" jsonschema:"Top-left corner of the selection"`
	Width      int     `json:"width" jsonschema:"Dimensions of the selection"`
	Height     int     `json:"height" jsonschema:"Dimensions of the selection"`
	Operation  *string `json:"operation" jsonschema:"\"replace\" (default), \"add\", \"subtract\", \"intersect\""`
	Feather    float64 `json:"feather" jsonschema:"Feather radius in pixels (default 0 = no feather)"`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetDefaults applies the defaults documented for the select_rectangle tool.
func (in *SelectRectangleInput) SetDefaults() {
	if in.Operation == nil {
		in.Operation = ptr("replace")
	}
}

// SelectEllipseInput holds the arguments for the select_ellipse tool.
type SelectEllipseInput struct {
	X          int     `json:"x" jsonschema:"Top-left corner of the bounding box"`
	Y          int     `json:"y" jsonschema:"Top-left corner of the bounding box"`
	Width      int     `json:"width" jsonschema:"Bounding box dimensions"`
	Height     int     `json:"height" jsonschema:"Bounding box dimensions"`
	Operation  *string `json:"operation" jsonschema:"\"replace\" (default), \"add\", \"subtract\", \"intersect\""`
	Feather    float64 `json:"feather" jsonschema:"Feather radius in pixels (default 0)"`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetDefaults applies the defaults documented for the select_ellipse tool.
func (in *SelectEllipseInput) SetDefaults() {
	if in.Operation == nil {
		in.Operation = ptr("replace")
	}
}

// SelectByColorInput holds the arguments for the select_by_color tool.
type SelectByColorInput struct {
	Color      string  `json:"color" jsonschema:"Target color as CSS name, hex (#rrggbb), or rgb() string"`
	Threshold  *int    `json:"threshold" jsonschema:"Color similarity tolerance 0-255 (default 15)"`
	Operation  *string `json:"operation" jsonschema:"\"replace\" (default), \"add\", \"subtract\", \"intersect\""`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
	LayerName  *string `json:"layer_name" jsonschema:"Layer to sample from; defaults to active layer"`
}

// SetDefaults applies the defaults documented for the select_by_color tool.
func (in *SelectByColorInput) SetDefaults() {
	if in.Threshold == nil {
		in.Threshold = ptr(15)
	}
	if in.Operation == nil {
		in.Operation = ptr("replace")
	}
}

// SelectAllInput holds the arguments for the select_all tool.
type SelectAllInput struct {
	ImageIndex int `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SelectNoneInput holds the arguments for the select_none tool.
type SelectNoneInput struct {
	ImageIndex int `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// InvertSelectionInput holds the arguments for the invert_selection tool.
type InvertSelectionInput struct {
	ImageIndex int `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// ModifySelectionInput holds the arguments for the modify_selection tool.
type ModifySelectionInput struct {
	Operation  string  `json:"operation" jsonschema:"\"grow\", \"shrink\", \"feather\", \"border\", \"sharpen\""`
	Amount     float64 `json:"amount" jsonschema:"Pixel radius for grow/shrink/feather/border; ignored for sharpen"`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// CreateLayerInput holds the arguments for the create_layer tool.
type CreateLayerInput struct {
	Name       *string  `json:"name" jsonschema:"Layer name (default \"New Layer\")"`
	Width      *int     `json:"width" jsonschema:"Layer dimensions; defaults to image dimensions"`
	Height     *int     `json:"height" jsonschema:"Layer dimensions; defaults to image dimensions"`
	Fill       *string  `json:"fill" jsonschema:"Initial fill — \"transparent\" (default), \"white\", \"black\", or any CSS color"`
	Opacity    *float64 `json:"opacity" jsonschema:"Layer opacity 0-100 (default 100)"`
	BlendMode  *string  `json:"blend_mode" jsonschema:"GIMP layer mode name — \"NORMAL\" (default), \"MULTIPLY\", \"SCREEN\", etc."`
	Position   *int     `json:"position" jsonschema:"Stack position — -1 = top (default), 0 = bottom"`
	ImageIndex int      `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetDefaults applies the defaults documented for the create_layer tool.
func (in *CreateLayerInput) SetDefaults() {
	if in.Name == nil {
		in.Name = ptr("New Layer")
	}
	if in.Fill == nil {
		in.Fill = ptr("transparent")
	}
	if in.Opacity == nil {
		in.Opacity = ptr(100.0)
	}
	if in.BlendMode == nil {
		in.BlendMode = ptr("NORMAL")
	}
	if in.Position == nil {
		in.Position = ptr(-1)
	}
}

// AddImageLayerInput holds the arguments for the add_image_layer tool.
type AddImageLayerInput struct {
	FilePath   string   `json:"file_path" jsonschema:"Absolute path to the image file to place"`
	X          int      `json:"x" jsonschema:"Top-left corner for the layer (default 0)"`
	Y          int      `json:"y" jsonschema:"Top-left corner for the layer (default 0)"`
	Align      *string  `json:"align" jsonschema:"Horizontal placement: \"left\" (default), \"center\", or \"right\""`
	Width      *int     `json:"width" jsonschema:"Scale the layer to this width; keeps aspect ratio if height is omitted"`
	Height     *int     `json:"height" jsonschema:"Scale the layer to this height; keeps aspect ratio if width is omitted"`
	Name       *string  `json:"name" jsonschema:"Name for the new layer"`
	Opacity    *float64 `json:"opacity" jsonschema:"Layer opacity 0-100 (default 100)"`
	Position   *int     `json:"position" jsonschema:"Stack position — -1 = top (default), 0 = bottom"`
	ImageIndex int      `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetDefaults applies the defaults documented for the add_image_layer tool.
func (in *AddImageLayerInput) SetDefaults() {
	if in.Opacity == nil {
		in.Opacity = ptr(100.0)
	}
	if in.Position == nil {
		in.Position = ptr(-1)
	}
}

// DuplicateLayerInput holds the arguments for the duplicate_layer tool.
type DuplicateLayerInput struct {
	LayerName  *string `json:"layer_name" jsonschema:"Name of the layer to duplicate; defaults to active layer"`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// DeleteLayerInput holds the arguments for the delete_layer tool.
type DeleteLayerInput struct {
	LayerName  *string `json:"layer_name" jsonschema:"Name of the layer to delete"`
	LayerIndex *int    `json:"layer_index" jsonschema:"Position index of the layer (alternative to layer_name)"`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// RenameLayerInput holds the arguments for the rename_layer tool.
type RenameLayerInput struct {
	NewName    string  `json:"new_name" jsonschema:"New name for the layer"`
	OldName    *string `json:"old_name" jsonschema:"Current name of the layer to rename"`
	LayerIndex *int    `json:"layer_index" jsonschema:"Position index alternative to old_name"`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetLayerPropertiesInput holds the arguments for the set_layer_properties tool.
type SetLayerPropertiesInput struct {
	LayerName  *string  `json:"layer_name" jsonschema:"Identify the layer (defaults to active layer)"`
	LayerIndex *int     `json:"layer_index" jsonschema:"Identify the layer (defaults to active layer)"`
	Opacity    *float64 `json:"opacity" jsonschema:"New opacity 0-100 (omit to leave unchanged)"`
	BlendMode  *string  `json:"blend_mode" jsonschema:"New GIMP layer mode name (omit to leave unchanged)"`
	Visible    *bool    `json:"visible" jsonschema:"True/False visibility (omit to leave unchanged)"`
	ImageIndex int      `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetLayerOffsetsInput holds the arguments for the set_layer_offsets tool.
type SetLayerOffsetsInput struct {
	X          int     `json:"x" jsonschema:"New top-left corner of the layer"`
	Y          int     `json:"y" jsonschema:"New top-left corner of the layer"`
	Align      *string `json:"align" jsonschema:"Horizontal placement: \"left\" (default), \"center\", or \"right\""`
	LayerName  *string `json:"layer_name" jsonschema:"Identify the layer (defaults to active layer)"`
	LayerIndex *int    `json:"layer_index" jsonschema:"Identify the layer by stack position (defaults to active layer)"`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// ReorderLayerInput holds the arguments for the reorder_layer tool.
type ReorderLayerInput struct {
	NewPosition int     `json:"new_position" jsonschema:"Target stack index (0 = bottom)"`
	LayerName   *string `json:"layer_name" jsonschema:"Identify the layer (defaults to active layer)"`
	LayerIndex  *int    `json:"layer_index" jsonschema:"Identify the layer (defaults to active layer)"`
	ImageIndex  int     `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// FlattenImageInput holds the arguments for the flatten_image tool.
type FlattenImageInput struct {
	ImageIndex int `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// MergeVisibleLayersInput holds the arguments for the merge_visible_layers tool.
type MergeVisibleLayersInput struct {
	ImageIndex int `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// ListLayersInput holds the arguments for the list_layers tool.
type ListLayersInput struct {
	ImageIndex int `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// FillLayerInput holds the arguments for the fill_layer tool.
type FillLayerInput struct {
	Color      string  `json:"color" jsonschema:"Fill color as CSS name, hex, or rgb() string"`
	LayerName  *string `json:"layer_name" jsonschema:"Layer to fill; defaults to active layer"`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// FillSelectionInput holds the arguments for the fill_selection tool.
type FillSelectionInput struct {
	Color      *string `json:"color" jsonschema:"Fill color as CSS name, hex, or rgb() string (used when fill_type is omitted)"`
	FillType   *string `json:"fill_type" jsonschema:"Fill type override: \"foreground\", \"background\", or \"transparent\""`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
	LayerName  *string `json:"layer_name" jsonschema:"Target layer; defaults to active layer"`
}

// SetColorsInput holds the arguments for the set_colors tool.
type SetColorsInput struct {
	Foreground *string `json:"foreground" jsonschema:"New foreground color (CSS name, hex, rgb()); omit to leave unchanged"`
	Background *string `json:"background" jsonschema:"New background color; omit to leave unchanged"`
}

// DrawLineInput holds the arguments for the draw_line tool.
type DrawLineInput struct {
	X1         float64  `json:"x1" jsonschema:"Start point"`
	Y1         float64  `json:"y1" jsonschema:"Start point"`
	X2         float64  `json:"x2" jsonschema:"End point"`
	Y2         float64  `json:"y2" jsonschema:"End point"`
	Color      *string  `json:"color" jsonschema:"Stroke color (CSS / hex / rgb); uses current foreground if omitted"`
	Width      *float64 `json:"width" jsonschema:"Stroke width in pixels (default 2.0)"`
	Tool       *string  `json:"tool" jsonschema:"\"pencil\" (default, hard edge) or \"paintbrush\" (soft edge)"`
	LayerName  *string  `json:"layer_name" jsonschema:"Target layer; defaults to active layer"`
	ImageIndex int      `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetDefaults applies the defaults documented for the draw_line tool.
func (in *DrawLineInput) SetDefaults() {
	if in.Width == nil {
		in.Width = ptr(2.0)
	}
	if in.Tool == nil {
		in.Tool = ptr("pencil")
	}
}

// DrawRectangleInput holds the arguments for the draw_rectangle tool.
type DrawRectangleInput struct {
	X          int      `json:"x" jsonschema:"Top-left corner"`
	Y          int      `json:"y" jsonschema:"Top-left corner"`
	Width      int      `json:"width" jsonschema:"Rectangle dimensions"`
	Height     int      `json:"height" jsonschema:"Rectangle dimensions"`
	Color      *string  `json:"color" jsonschema:"Stroke color; uses current foreground if omitted"`
	LineWidth  *float64 `json:"line_width" jsonschema:"Stroke width in pixels (default 2.0)"`
	LayerName  *string  `json:"layer_name" jsonschema:"Target layer; defaults to active layer"`
	ImageIndex int      `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetDefaults applies the defaults documented for the draw_rectangle tool.
func (in *DrawRectangleInput) SetDefaults() {
	if in.LineWidth == nil {
		in.LineWidth = ptr(2.0)
	}
}

// DrawEllipseInput holds the arguments for the draw_ellipse tool.
type DrawEllipseInput struct {
	X          int      `json:"x" jsonschema:"Top-left corner of the bounding box"`
	Y          int      `json:"y" jsonschema:"Top-left corner of the bounding box"`
	Width      int      `json:"width" jsonschema:"Bounding box dimensions"`
	Height     int      `json:"height" jsonschema:"Bounding box dimensions"`
	Color      *string  `json:"color" jsonschema:"Stroke color; uses current foreground if omitted"`
	LineWidth  *float64 `json:"line_width" jsonschema:"Stroke width in pixels (default 2.0)"`
	LayerName  *string  `json:"layer_name" jsonschema:"Target layer; defaults to active layer"`
	ImageIndex int      `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetDefaults applies the defaults documented for the draw_ellipse tool.
func (in *DrawEllipseInput) SetDefaults() {
	if in.LineWidth == nil {
		in.LineWidth = ptr(2.0)
	}
}

// FillRectangleInput holds the arguments for the fill_rectangle tool.
type FillRectangleInput struct {
	X          int     `json:"x" jsonschema:"Top-left corner"`
	Y          int     `json:"y" jsonschema:"Top-left corner"`
	Width      int     `json:"width" jsonschema:"Rectangle dimensions"`
	Height     int     `json:"height" jsonschema:"Rectangle dimensions"`
	Color      string  `json:"color" jsonschema:"Fill color (CSS name, hex, or rgb() string)"`
	LayerName  *string `json:"layer_name" jsonschema:"Target layer; defaults to active layer"`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// FillEllipseInput holds the arguments for the fill_ellipse tool.
type FillEllipseInput struct {
	X          int     `json:"x" jsonschema:"Top-left corner of the bounding box"`
	Y          int     `json:"y" jsonschema:"Top-left corner of the bounding box"`
	Width      int     `json:"width" jsonschema:"Bounding box dimensions"`
	Height     int     `json:"height" jsonschema:"Bounding box dimensions"`
	Color      string  `json:"color" jsonschema:"Fill color (CSS name, hex, or rgb() string)"`
	LayerName  *string `json:"layer_name" jsonschema:"Target layer; defaults to active layer"`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// GradientFillInput holds the arguments for the gradient_fill tool.
type GradientFillInput struct {
	Color1       *string  `json:"color1" jsonschema:"Start color (default \"black\")"`
	Color2       *string  `json:"color2" jsonschema:"End color (default \"white\")"`
	X1           float64  `json:"x1" jsonschema:"Gradient start point (default top-left 0,0)"`
	Y1           float64  `json:"y1" jsonschema:"Gradient start point (default top-left 0,0)"`
	X2           *float64 `json:"x2" jsonschema:"Gradient end point (defaults to bottom-right of image)"`
	Y2           *float64 `json:"y2" jsonschema:"Gradient end point (defaults to bottom-right of image)"`
	GradientType *string  `json:"gradient_type" jsonschema:"\"linear\" (default) or \"radial\""`
	LayerName    *string  `json:"layer_name" jsonschema:"Target layer; defaults to active layer"`
	ImageIndex   int      `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetDefaults applies the defaults documented for the gradient_fill tool.
func (in *GradientFillInput) SetDefaults() {
	if in.Color1 == nil {
		in.Color1 = ptr("black")
	}
	if in.Color2 == nil {
		in.Color2 = ptr("white")
	}
	if in.GradientType == nil {
		in.GradientType = ptr("linear")
	}
}

// AddTextInput holds the arguments for the add_text tool.
type AddTextInput struct {
	Text       string  `json:"text" jsonschema:"The text string to render"`
	X          int     `json:"x" jsonschema:"Position of the text layer's top-left corner (default 0, 0)"`
	Y          int     `json:"y" jsonschema:"Position of the text layer's top-left corner (default 0, 0)"`
	Font       *string `json:"font" jsonschema:"Font family name — \"Sans\" (default), \"Serif\", etc."`
	Size       *int    `json:"size" jsonschema:"Font size in pixels (default 24)"`
	Color      *string `json:"color" jsonschema:"Text color (CSS name, hex, or rgb() string; default \"black\")"`
	Align      *string `json:"align" jsonschema:"Horizontal placement: \"left\" (default, uses x), \"center\", or \"right\" (x is the right margin)"`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetDefaults applies the defaults documented for the add_text tool.
func (in *AddTextInput) SetDefaults() {
	if in.Font == nil {
		in.Font = ptr("Sans")
	}
	if in.Size == nil {
		in.Size = ptr(24)
	}
	if in.Color == nil {
		in.Color = ptr("black")
	}
}

// EditTextInput holds the arguments for the edit_text tool.
type EditTextInput struct {
	LayerName  string   `json:"layer_name" jsonschema:"Name of the text layer to edit"`
	Text       *string  `json:"text" jsonschema:"New text content (omit to leave unchanged)"`
	Font       *string  `json:"font" jsonschema:"New font family (omit to leave unchanged)"`
	Size       *float64 `json:"size" jsonschema:"New font size in pixels (omit to leave unchanged)"`
	Color      *string  `json:"color" jsonschema:"New text color (omit to leave unchanged)"`
	ImageIndex int      `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// ListFontsInput holds the arguments for the list_fonts tool.
type ListFontsInput struct {
	Filter *string `json:"filter" jsonschema:"Optional string to filter font names (case-insensitive substring match)"`
}

// ApplyDropShadowInput holds the arguments for the apply_drop_shadow tool.
type ApplyDropShadowInput struct {
	OffsetX    *int     `json:"offset_x" jsonschema:"Shadow offset in pixels (default 5, 5)"`
	OffsetY    *int     `json:"offset_y" jsonschema:"Shadow offset in pixels (default 5, 5)"`
	BlurRadius *float64 `json:"blur_radius" jsonschema:"Shadow softness radius (default 10)"`
	Color      *string  `json:"color" jsonschema:"Shadow color (default \"black\")"`
	Opacity    *float64 `json:"opacity" jsonschema:"Shadow opacity 0-100 (default 60)"`
	LayerName  *string  `json:"layer_name" jsonschema:"Target layer; defaults to active layer"`
	ImageIndex int      `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetDefaults applies the defaults documented for the apply_drop_shadow tool.
func (in *ApplyDropShadowInput) SetDefaults() {
	if in.OffsetX == nil {
		in.OffsetX = ptr(5)
	}
	if in.OffsetY == nil {
		in.OffsetY = ptr(5)
	}
	if in.BlurRadius == nil {
		in.BlurRadius = ptr(10.0)
	}
	if in.Color == nil {
		in.Color = ptr("black")
	}
	if in.Opacity == nil {
		in.Opacity = ptr(60.0)
	}
}

// ApplyGeglFilterInput holds the arguments for the apply_gegl_filter tool.
type ApplyGeglFilterInput struct {
	Operation  string             `json:"operation" jsonschema:"GEGL operation name, e.g. \"gegl:cartoon\""`
	Settings   map[string]float64 `json:"settings" jsonschema:"Numeric properties for the operation, e.g. {\"mask-radius\": 7.0}"`
	LayerName  *string            `json:"layer_name" jsonschema:"Target layer; defaults to active layer"`
	ImageIndex int                `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// ApplyGaussianBlurInput holds the arguments for the apply_gaussian_blur tool.
type ApplyGaussianBlurInput struct {
	Radius     *float64 `json:"radius" jsonschema:"Blur radius in pixels (default 5.0)"`
	LayerName  *string  `json:"layer_name" jsonschema:"Target layer; defaults to active layer"`
	ImageIndex int      `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetDefaults applies the defaults documented for the apply_gaussian_blur tool.
func (in *ApplyGaussianBlurInput) SetDefaults() {
	if in.Radius == nil {
		in.Radius = ptr(5.0)
	}
}

// ApplyPixelateInput holds the arguments for the apply_pixelate tool.
type ApplyPixelateInput struct {
	BlockSize  *int    `json:"block_size" jsonschema:"Size of each mosaic block in pixels (default 10)"`
	LayerName  *string `json:"layer_name" jsonschema:"Target layer; defaults to active layer"`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetDefaults applies the defaults documented for the apply_pixelate tool.
func (in *ApplyPixelateInput) SetDefaults() {
	if in.BlockSize == nil {
		in.BlockSize = ptr(10)
	}
}

// ApplyEmbossInput holds the arguments for the apply_emboss tool.
type ApplyEmbossInput struct {
	Azimuth    *float64 `json:"azimuth" jsonschema:"Light direction in degrees 0-360 (default 315 = top-left)"`
	Elevation  *float64 `json:"elevation" jsonschema:"Light elevation angle 0-90 (default 45)"`
	Depth      *float64 `json:"depth" jsonschema:"Effect depth/intensity (default 2)"`
	LayerName  *string  `json:"layer_name" jsonschema:"Target layer; defaults to active layer"`
	ImageIndex int      `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetDefaults applies the defaults documented for the apply_emboss tool.
func (in *ApplyEmbossInput) SetDefaults() {
	if in.Azimuth == nil {
		in.Azimuth = ptr(315.0)
	}
	if in.Elevation == nil {
		in.Elevation = ptr(45.0)
	}
	if in.Depth == nil {
		in.Depth = ptr(2.0)
	}
}

// ApplyVignetteInput holds the arguments for the apply_vignette tool.
type ApplyVignetteInput struct {
	Softness   *float64 `json:"softness" jsonschema:"Edge softness / fade width (default 3.0)"`
	Shape      *float64 `json:"shape" jsonschema:"Shape factor — 1.0 = elliptical (default), values >1 = more rectangular"`
	LayerName  *string  `json:"layer_name" jsonschema:"Target layer; defaults to active layer"`
	ImageIndex int      `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetDefaults applies the defaults documented for the apply_vignette tool.
func (in *ApplyVignetteInput) SetDefaults() {
	if in.Softness == nil {
		in.Softness = ptr(3.0)
	}
	if in.Shape == nil {
		in.Shape = ptr(1.0)
	}
}

// ApplyNoiseInput holds the arguments for the apply_noise tool.
type ApplyNoiseInput struct {
	Amount     *float64 `json:"amount" jsonschema:"Noise intensity 0.0-1.0 (default 0.2)"`
	LayerName  *string  `json:"layer_name" jsonschema:"Target layer; defaults to active layer"`
	ImageIndex int      `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetDefaults applies the defaults documented for the apply_noise tool.
func (in *ApplyNoiseInput) SetDefaults() {
	if in.Amount == nil {
		in.Amount = ptr(0.2)
	}
}

// ExportIconSizesInput holds the arguments for the export_icon_sizes tool.
type ExportIconSizesInput struct {
	OutputDir        string  `json:"output_dir" jsonschema:"Directory to write icon files into"`
	Platform         *string `json:"platform" jsonschema:"\"android\" (default) or \"ios\""`
	SourceImageIndex int     `json:"source_image_index" jsonschema:"Image to use as source (default 0)"`
	Format           *string `json:"format" jsonschema:"Output format — \"png\" (default)"`
}

// SetDefaults applies the defaults documented for the export_icon_sizes tool.
func (in *ExportIconSizesInput) SetDefaults() {
	if in.Platform == nil {
		in.Platform = ptr("android")
	}
	if in.Format == nil {
		in.Format = ptr("png")
	}
}

// ExportWebOptimizedInput holds the arguments for the export_web_optimized tool.
type ExportWebOptimizedInput struct {
	OutputDir      string `json:"output_dir" jsonschema:"Directory to write output files"`
	JPEGQuality    *int   `json:"jpeg_quality" jsonschema:"JPEG quality 1-100 (default 85)"`
	PNGCompression *int   `json:"png_compression" jsonschema:"PNG compression level 0-9 (default 9)"`
	MaxWidth       *int   `json:"max_width" jsonschema:"Optional scaling before export"`
	MaxHeight      *int   `json:"max_height" jsonschema:"Optional scaling before export"`
	ImageIndex     int    `json:"image_index" jsonschema:"Source image index (default 0)"`
}

// SetDefaults applies the defaults documented for the export_web_optimized tool.
func (in *ExportWebOptimizedInput) SetDefaults() {
	if in.JPEGQuality == nil {
		in.JPEGQuality = ptr(85)
	}
	if in.PNGCompression == nil {
		in.PNGCompression = ptr(9)
	}
}

// WarpRegionInput holds the arguments for the warp_region tool.
type WarpRegionInput struct {
	Vectors    []any   `json:"vectors" jsonschema:"List of warp stroke dicts, each with: - x, y      : center of the warp influence (pixels) - dx, dy    : push direction — negative dy = push upward - radius    : influence radius in pixels (default: 40) - amount    : deform strength 0–1 (default: 0.3)"`
	ImageIndex int     `json:"image_index" jsonschema:"Which open image to edit (default: 0)"`
	LayerName  *string `json:"layer_name" jsonschema:"Target layer; omit to use the active/top layer"`
}

// BatchResizeInput holds the arguments for the batch_resize tool.
type BatchResizeInput struct {
	Width          *int     `json:"width" jsonschema:"Target dimensions in pixels (provide one or both)"`
	Height         *int     `json:"height" jsonschema:"Target dimensions in pixels (provide one or both)"`
	ScaleFactor    *float64 `json:"scale_factor" jsonschema:"Proportional scale (e.g. 0.5 = 50%); overrides width/height if set"`
	MaintainAspect *bool    `json:"maintain_aspect" jsonschema:"Preserve aspect ratio when only one dimension is given (default True)"`
}

// SetDefaults applies the defaults documented for the batch_resize tool.
func (in *BatchResizeInput) SetDefaults() {
	if in.MaintainAspect == nil {
		in.MaintainAspect = ptr(true)
	}
}

// ExportSpriteSheetInput holds the arguments for the export_sprite_sheet tool.
type ExportSpriteSheetInput struct {
	OutputPath string  `json:"output_path" jsonschema:"Absolute path for the output PNG file"`
	Columns    *int    `json:"columns" jsonschema:"Number of columns in the grid (defaults to square root of frame count)"`
	Padding    int     `json:"padding" jsonschema:"Pixel gap between frames (default 0)"`
	Source     *string `json:"source" jsonschema:"\"layers\" (each layer is a frame; default) or \"images\" (each open image)"`
	ImageIndex int     `json:"image_index" jsonschema:"Source image when source=\"layers\" (default 0)"`
}

// SetDefaults applies the defaults documented for the export_sprite_sheet tool.
func (in *ExportSpriteSheetInput) SetDefaults() {
	if in.Source == nil {
		in.Source = ptr("layers")
	}
}

// ExportSocialMediaKitInput holds the arguments for the export_social_media_kit tool.
type ExportSocialMediaKitInput struct {
	OutputDir  string `json:"output_dir" jsonschema:"Directory to write output files"`
	Platforms  []any  `json:"platforms" jsonschema:"List of platform names to export (omit for all five)"`
	ImageIndex int    `json:"image_index" jsonschema:"Source image index (default 0)"`
}

// ListImagesInput holds the arguments for the list_images tool.
type ListImagesInput struct{}

// SetActiveImageInput holds the arguments for the set_active_image tool.
type SetActiveImageInput struct {
	ImageIndex int `json:"image_index" jsonschema:"Index of the image to activate (from list_images)"`
}

// UndoInput holds the arguments for the undo tool.
type UndoInput struct {
	Steps      *int `json:"steps" jsonschema:"Number of undo steps (default 1)"`
	ImageIndex int  `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetDefaults applies the defaults documented for the undo tool.
func (in *UndoInput) SetDefaults() {
	if in.Steps == nil {
		in.Steps = ptr(1)
	}
}

// RedoInput holds the arguments for the redo tool.
type RedoInput struct {
	Steps      *int `json:"steps" jsonschema:"Number of redo steps (default 1)"`
	ImageIndex int  `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetDefaults applies the defaults documented for the redo tool.
func (in *RedoInput) SetDefaults() {
	if in.Steps == nil {
		in.Steps = ptr(1)
	}
}

// ConvertColorModeInput holds the arguments for the convert_color_mode tool.
type ConvertColorModeInput struct {
	Mode       string `json:"mode" jsonschema:"\"RGB\", \"GRAY\", or \"INDEXED\""`
	NumColors  *int   `json:"num_colors" jsonschema:"Number of colors for INDEXED mode (default 256)"`
	ImageIndex int    `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetDefaults applies the defaults documented for the convert_color_mode tool.
func (in *ConvertColorModeInput) SetDefaults() {
	if in.NumColors == nil {
		in.NumColors = ptr(256)
	}
}

// CloseImageInput holds the arguments for the close_image tool.
type CloseImageInput struct {
	ImageIndex int  `json:"image_index" jsonschema:"Index of the image to close (default 0)"`
	SaveFirst  bool `json:"save_first" jsonschema:"If True, save as XCF before closing (default False)"`
	Force      bool `json:"force" jsonschema:"Close even with unsaved changes, discarding them (default False)"`
}

// GetSelectionBoundsInput holds the arguments for the get_selection_bounds tool.
type GetSelectionBoundsInput struct {
	ImageIndex int `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// GetPixelColorInput holds the arguments for the get_pixel_color tool.
type GetPixelColorInput struct {
	X          int     `json:"x" jsonschema:"Pixel coordinates"`
	Y          int     `json:"y" jsonschema:"Pixel coordinates"`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
	LayerName  *string `json:"layer_name" jsonschema:"Layer to sample from; defaults to active layer"`
}

// GetHistogramInput holds the arguments for the get_histogram tool.
type GetHistogramInput struct {
	Channel    *string `json:"channel" jsonschema:"\"value\" (all; default), \"red\", \"green\", \"blue\", \"alpha\""`
	ImageIndex int     `json:"image_index" jsonschema:"Target image index (default 0)"`
}

// SetDefaults applies the defaults documented for the get_histogram tool.
func (in *GetHistogramInput) SetDefaults() {
	if in.Channel == nil {
		in.Channel = ptr("value")
	}
}

// registerGenerated wires up every tool that forwards its arguments to the
// plug-in unchanged and returns the plug-in's results verbatim.
func registerGenerated(r *registrar) {
	addObject[NewCanvasInput](r, toolDef{
		Name:        "new_canvas",
		Command:     "new_canvas",
		Required:    []string{"width", "height"},
		Description: "Create a new blank canvas in GIMP and open it in a display window.\n\nParameters:\n- width: Canvas width in pixels\n- height: Canvas height in pixels\n- name: Layer/image name (default: \"Untitled\")\n- color_mode: \"RGB\" (default), \"RGBA\", \"GRAY\", \"GRAYA\"\n- fill: Fill color for the background layer. Any CSS color name or\n        hex string: \"white\" (default), \"black\", \"transparent\",\n        \"#FF5733\", \"rgb(100,200,50)\", etc.\n- resolution: DPI resolution (default: 72)\n\nReturns:\n- image_id: internal GIMP image ID\n- width / height: confirmed dimensions\n- color_mode: confirmed mode\n- display_opened: whether a GIMP window was opened\n\nExamples:\n- new_canvas(1024, 1024) — white 1024x1024 RGB canvas\n- new_canvas(1920, 1080, name=\"Background\", fill=\"black\")\n- new_canvas(512, 512, color_mode=\"RGBA\", fill=\"transparent\")",
	})
	addImage[GetImageBitmapInput](r, toolDef{
		Name:        "get_image_bitmap",
		Command:     "get_image_bitmap",
		Required:    nil,
		Description: "Get the current open image in GIMP as an Image object with optional scaling and region selection.\n\nNo size restrictions — pass any max_width/max_height you need.\nFor large images, omit max_width/max_height to get the full resolution.\n\nSupports two main use cases:\n1. Full image with optional scaling (pass max_width/max_height)\n2. Region extraction with optional scaling (pass region dict)\n\nParameters:\n- max_width, max_height: Target dimensions for scaling (aspect-ratio preserved).\n  Omit for full resolution.\n- region: Dictionary with keys:\n    - origin_x, origin_y: Top-left corner of region to extract\n    - width, height: Dimensions of region to extract\n    - max_width, max_height: Optional scaling for the extracted region\n\nExamples:\n- Full image at full res: get_image_bitmap()\n- Full image scaled: get_image_bitmap(max_width=2048, max_height=2048)\n- Region: get_image_bitmap(region={\"origin_x\": 0, \"origin_y\": 0, \"width\": 512, \"height\": 512})\n\nReturns:\n- Image object containing PNG data in MCP-compliant format\n- Includes width, height, and base64-encoded image data\n\nThe returned Image object automatically handles base64 encoding and MIME types\naccording to the Model Context Protocol specification.\n\nRaises:\n- RuntimeError if no image is open, region is invalid, or export fails",
	})
	addObject[GetImageMetadataInput](r, toolDef{
		Name:        "get_image_metadata",
		Command:     "get_image_metadata",
		Required:    nil,
		Description: "Get metadata about the current open image in GIMP without the bitmap data.\n\nReturns detailed information about the currently active image including:\n- Image dimensions (width, height)\n- Color mode and base type\n- Number of layers and channels\n- File information if available\n- Layer structure and properties\n\nThis is much faster than get_image_bitmap() since it doesn't export the actual image data.\nPerfect for when you only need to know image properties for decision making.\n\nReturns:\n- Dictionary containing comprehensive image metadata\n- Raises exception if no images are open",
	})
	addObject[GetGimpInfoInput](r, toolDef{
		Name:        "get_gimp_info",
		Command:     "get_gimp_info",
		Required:    nil,
		Description: "Get comprehensive information about the GIMP installation and environment.\n\nReturns detailed information about GIMP that AI assistants need to understand\nthe current environment, including:\n- GIMP version and build information\n- Installation paths and directories\n- Available plugins and procedures\n- System configuration\n- Runtime environment details\n\nThis information helps AI assistants provide better support and troubleshooting\nby understanding the specific GIMP setup they're working with.\n\nReturns:\n- Dictionary containing comprehensive GIMP environment information\n- Raises exception if GIMP connection fails",
	})
	addObject[GetContextStateInput](r, toolDef{
		Name:        "get_context_state",
		Command:     "get_context_state",
		Required:    nil,
		Description: "Get the current GIMP context state (colors, brush, settings).\n\nIMPORTANT: Context state can be changed by the user in GIMP UI at any time.\nCheck context state before operations that depend on specific settings.\n\nReturns information about:\n- Foreground and background colors (RGB/RGBA values)\n- Current brush and its properties\n- Opacity setting (0-100%)\n- Paint/blend mode\n- Feather state and radius\n- Antialiasing state\n\nUse cases:\n- Verify colors before drawing operations\n- Check if feathering is enabled (avoid unwanted blurry edges)\n- Ensure correct opacity and blend mode\n- Detect if user changed settings in GIMP UI\n\nReturns:\n- Dictionary containing current context state\n- Raises exception if unable to get context state",
	})
	addObject[DescribeProcedureInput](r, toolDef{
		Name:        "describe_procedure",
		Command:     "describe_procedure",
		Required:    []string{"api_path"},
		Description: "List the arguments a GIMP PDB procedure takes.\n\nUse this before call_api to discover exact argument names and types, which\nGIMP requires to match precisely.\n\nParameters:\n- api_path: The PDB procedure name, e.g. \"gimp-image-scale\"\n\nReturns:\n- procedure: the name queried\n- arguments: ordered list of {name, type, blurb}\n\nExample:\n    describe_procedure(api_path=\"gimp-drawable-get-pixel\")\n    -> arguments: drawable (GimpDrawable), x-coord (gint), y-coord (gint)",
	})
	addObject[OpenImageInput](r, toolDef{
		Name:        "open_image",
		Command:     "open_image",
		Required:    []string{"file_path"},
		Description: "Open an image file in GIMP and create a display window.\n\nParameters:\n- file_path: Absolute path to the image file to open (PNG, JPEG, TIFF, etc.)\n\nReturns:\n- image_id: internal GIMP image ID\n- width / height: image dimensions in pixels\n- color_mode: RGB / Grayscale / Indexed\n- num_layers: number of layers in the image\n- display_opened: whether a GIMP display window was created",
	})
	addObject[SaveXcfInput](r, toolDef{
		Name:        "save_xcf",
		Command:     "save_xcf",
		Required:    []string{"file_path"},
		Description: "Save the current image as a GIMP XCF file (preserves all layers and metadata).\n\nParameters:\n- file_path: Absolute path for the output .xcf file\n- image_index: Index of the image to save (default 0 = first open image)\n\nReturns:\n- status: \"success\" or \"error\"\n- file_path: confirmed output path",
	})
	addObject[ExportImageInput](r, toolDef{
		Name:        "export_image",
		Command:     "export_image",
		Required:    []string{"file_path"},
		Description: "Export the current image to a raster file (PNG, JPEG, WEBP, TIFF).\n\nParameters:\n- file_path: Absolute path for the output file\n- format: Output format — \"png\" (default), \"jpeg\", \"webp\", \"tiff\"\n- quality: JPEG/WEBP quality 1-100 (default 90; ignored for PNG/TIFF)\n- flatten: Flatten all layers before export (default True)\n- image_index: Index of the image to export (default 0)\n\nReturns:\n- status, file_path, format, file_size_bytes",
	})
	addObject[BatchExportInput](r, toolDef{
		Name:        "batch_export",
		Command:     "batch_export",
		Required:    []string{"output_dir"},
		Description: "Export all open images (or a specific one) to a directory.\n\nParameters:\n- output_dir: Directory to write exported files into\n- format: \"png\", \"jpeg\", \"webp\", \"tiff\" (default \"png\")\n- quality: JPEG/WEBP quality (default 90)\n- name_pattern: Filename template — use {name} for image name, {index} for position\n- image_index: If set, export only that image; omit to export all open images\n\nReturns:\n- exported: list of {file_path, name, width, height}\n- count: number of files written\n- errors: list of any export errors",
	})
	addObject[AutoLevelsInput](r, toolDef{
		Name:        "auto_levels",
		Command:     "auto_levels",
		Required:    nil,
		Description: "Automatically stretch the tonal range of an image (auto levels / auto stretch contrast).\n\nParameters:\n- image_index: Index of the target image (default 0)\n- layer_name: Name of the layer to adjust; defaults to active layer\n\nReturns status dict.",
	})
	addObject[AdjustCurvesInput](r, toolDef{
		Name:        "adjust_curves",
		Command:     "adjust_curves",
		Required:    nil,
		Description: "Adjust tonal curves for a layer.\n\nParameters:\n- preset: Built-in curve shape — \"s_curve\" (default), \"lighten\", \"darken\", \"contrast\"\n- points: Custom control points as [[input, output], ...] override (overrides preset)\n- channel: \"value\" (all), \"red\", \"green\", \"blue\", \"alpha\"\n- image_index: Target image index (default 0)\n- layer_name: Layer to adjust; defaults to active layer\n\nReturns status dict.",
	})
	addObject[AdjustBrightnessContrastInput](r, toolDef{
		Name:        "adjust_brightness_contrast",
		Command:     "adjust_brightness_contrast",
		Required:    nil,
		Description: "Adjust brightness and contrast of a layer.\n\nParameters:\n- brightness: -127 to +127 (default 0)\n- contrast: -127 to +127 (default 0)\n- image_index: Target image index (default 0)\n- layer_name: Layer to adjust; defaults to active layer\n\nReturns status dict.",
	})
	addObject[AdjustHueSaturationInput](r, toolDef{
		Name:        "adjust_hue_saturation",
		Command:     "adjust_hue_saturation",
		Required:    nil,
		Description: "Adjust hue, saturation, and lightness of a layer.\n\nParameters:\n- hue: Hue rotation -180 to +180 (default 0)\n- saturation: Saturation shift -100 to +100 (default 0)\n- lightness: Lightness shift -100 to +100 (default 0)\n- color_range: \"all\", \"red\", \"yellow\", \"green\", \"cyan\", \"blue\", \"magenta\" (default \"all\")\n- image_index: Target image index (default 0)\n- layer_name: Layer to adjust; defaults to active layer\n\nReturns status dict.",
	})
	addObject[AdjustColorBalanceInput](r, toolDef{
		Name:        "adjust_color_balance",
		Command:     "adjust_color_balance",
		Required:    nil,
		Description: "Adjust color balance (shadows / midtones / highlights) of a layer.\n\nParameters:\n- cyan_red: -100 to +100 (negative = cyan, positive = red; default 0)\n- magenta_green: -100 to +100 (default 0)\n- yellow_blue: -100 to +100 (default 0)\n- range: \"shadows\", \"midtones\" (default), \"highlights\"\n- image_index: Target image index (default 0)\n- layer_name: Layer to adjust; defaults to active layer\n\nReturns status dict.",
	})
	addObject[SharpenInput](r, toolDef{
		Name:        "sharpen",
		Command:     "sharpen",
		Required:    nil,
		Description: "Sharpen a layer using unsharp mask.\n\nParameters:\n- amount: Sharpening strength 0-500 (default 50.0)\n- radius: Blur radius for the mask in pixels (default 3.0)\n- threshold: Minimum difference before sharpening is applied (default 0)\n- image_index: Target image index (default 0)\n- layer_name: Layer to sharpen; defaults to active layer\n\nReturns status dict.",
	})
	addObject[BlurInput](r, toolDef{
		Name:        "blur",
		Command:     "blur",
		Required:    nil,
		Description: "Apply Gaussian blur to a layer.\n\nParameters:\n- radius_x: Horizontal blur radius in pixels (default 5.0)\n- radius_y: Vertical blur radius in pixels (default 5.0)\n- image_index: Target image index (default 0)\n- layer_name: Layer to blur; defaults to active layer\n\nReturns status dict.",
	})
	addObject[DenoiseInput](r, toolDef{
		Name:        "denoise",
		Command:     "denoise",
		Required:    nil,
		Description: "Reduce noise in a layer using GEGL noise-reduction.\n\nParameters:\n- strength: Noise reduction strength 0-100 (default 50)\n- image_index: Target image index (default 0)\n- layer_name: Layer to denoise; defaults to active layer\n\nReturns status dict.",
	})
	addObject[DesaturateInput](r, toolDef{
		Name:        "desaturate",
		Command:     "desaturate",
		Required:    nil,
		Description: "Convert a layer to grayscale (desaturate).\n\nParameters:\n- mode: Desaturation algorithm — \"luminosity\" (default), \"luma\", \"average\", \"lightness\"\n- image_index: Target image index (default 0)\n- layer_name: Layer to desaturate; defaults to active layer\n\nReturns status dict.",
	})
	addObject[InvertColorsInput](r, toolDef{
		Name:        "invert_colors",
		Command:     "invert_colors",
		Required:    nil,
		Description: "Invert all colors in a layer (create a negative).\n\nParameters:\n- image_index: Target image index (default 0)\n- layer_name: Layer to invert; defaults to active layer\n\nReturns status dict.",
	})
	addObject[ScaleImageInput](r, toolDef{
		Name:        "scale_image",
		Command:     "scale_image",
		Required:    []string{"width", "height"},
		Description: "Scale an image to exact pixel dimensions.\n\nParameters:\n- width: Target width in pixels\n- height: Target height in pixels\n- interpolation: \"cubic\" (default), \"linear\", \"none\"\n- image_index: Target image index (default 0)\n\nReturns: {status, width, height}",
	})
	addObject[ScaleToFitInput](r, toolDef{
		Name:        "scale_to_fit",
		Command:     "scale_to_fit",
		Required:    []string{"max_width", "max_height"},
		Description: "Scale an image to fit within a bounding box, preserving aspect ratio.\n\nParameters:\n- max_width: Maximum allowed width in pixels\n- max_height: Maximum allowed height in pixels\n- interpolation: \"cubic\" (default), \"linear\", \"none\"\n- image_index: Target image index (default 0)\n\nReturns: {status, width, height} — final dimensions after scaling",
	})
	addObject[CropToSelectionInput](r, toolDef{
		Name:        "crop_to_selection",
		Command:     "crop_to_selection",
		Required:    nil,
		Description: "Crop the image canvas to the current selection bounds.\n\nParameters:\n- autocrop: If True, auto-detect crop bounds instead of using selection (default False)\n- image_index: Target image index (default 0)\n\nReturns: {status, x, y, width, height} — crop region applied",
	})
	addObject[CropToRectInput](r, toolDef{
		Name:        "crop_to_rect",
		Command:     "crop_to_rect",
		Required:    []string{"x", "y", "width", "height"},
		Description: "Crop the image canvas to an explicit rectangle.\n\nParameters:\n- x, y: Top-left corner of the crop rectangle\n- width, height: Dimensions of the crop rectangle\n- image_index: Target image index (default 0)\n\nReturns: {status, x, y, width, height}",
	})
	addObject[RotateImageInput](r, toolDef{
		Name:        "rotate_image",
		Command:     "rotate_image",
		Required:    []string{"angle"},
		Description: "Rotate the entire image.\n\nParameters:\n- angle: Rotation in degrees — 90, 180, 270 use lossless GIMP rotation;\n         other values rotate all layers with interpolation and flatten\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[FlipImageInput](r, toolDef{
		Name:        "flip_image",
		Command:     "flip_image",
		Required:    nil,
		Description: "Flip the entire image horizontally or vertically.\n\nParameters:\n- direction: \"horizontal\" (default) or \"vertical\"\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[ResizeCanvasInput](r, toolDef{
		Name:        "resize_canvas",
		Command:     "resize_canvas",
		Required:    []string{"width", "height"},
		Description: "Resize the image canvas without scaling the content.\n\nParameters:\n- width, height: New canvas dimensions in pixels\n- anchor: Position of existing content — \"center\" (default), \"top-left\", \"top\",\n          \"top-right\", \"left\", \"right\", \"bottom-left\", \"bottom\", \"bottom-right\"\n- fill: Color for new canvas areas — CSS color or \"transparent\"\n- image_index: Target image index (default 0)\n\nReturns: {status, width, height, offset_x, offset_y}",
	})
	addObject[SelectRectangleInput](r, toolDef{
		Name:        "select_rectangle",
		Command:     "select_rectangle",
		Required:    []string{"x", "y", "width", "height"},
		Description: "Create a rectangular selection.\n\nParameters:\n- x, y: Top-left corner of the selection\n- width, height: Dimensions of the selection\n- operation: \"replace\" (default), \"add\", \"subtract\", \"intersect\"\n- feather: Feather radius in pixels (default 0 = no feather)\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[SelectEllipseInput](r, toolDef{
		Name:        "select_ellipse",
		Command:     "select_ellipse",
		Required:    []string{"x", "y", "width", "height"},
		Description: "Create an elliptical selection.\n\nParameters:\n- x, y: Top-left corner of the bounding box\n- width, height: Bounding box dimensions\n- operation: \"replace\" (default), \"add\", \"subtract\", \"intersect\"\n- feather: Feather radius in pixels (default 0)\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[SelectByColorInput](r, toolDef{
		Name:        "select_by_color",
		Command:     "select_by_color",
		Required:    []string{"color"},
		Description: "Select regions by color similarity.\n\nParameters:\n- color: Target color as CSS name, hex (#rrggbb), or rgb() string\n- threshold: Color similarity tolerance 0-255 (default 15)\n- operation: \"replace\" (default), \"add\", \"subtract\", \"intersect\"\n- image_index: Target image index (default 0)\n- layer_name: Layer to sample from; defaults to active layer\n\nReturns status dict.",
	})
	addObject[SelectAllInput](r, toolDef{
		Name:        "select_all",
		Command:     "select_all",
		Required:    nil,
		Description: "Select the entire image canvas.\n\nParameters:\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[SelectNoneInput](r, toolDef{
		Name:        "select_none",
		Command:     "select_none",
		Required:    nil,
		Description: "Remove / deselect all selections.\n\nParameters:\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[InvertSelectionInput](r, toolDef{
		Name:        "invert_selection",
		Command:     "invert_selection",
		Required:    nil,
		Description: "Invert the current selection (select what is not selected).\n\nParameters:\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[ModifySelectionInput](r, toolDef{
		Name:        "modify_selection",
		Command:     "modify_selection",
		Required:    []string{"operation", "amount"},
		Description: "Grow, shrink, feather, border, or sharpen the current selection.\n\nParameters:\n- operation: \"grow\", \"shrink\", \"feather\", \"border\", \"sharpen\"\n- amount: Pixel radius for grow/shrink/feather/border; ignored for sharpen\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[CreateLayerInput](r, toolDef{
		Name:        "create_layer",
		Command:     "create_layer",
		Required:    nil,
		Description: "Create and insert a new layer into an image.\n\nParameters:\n- name: Layer name (default \"New Layer\")\n- width, height: Layer dimensions; defaults to image dimensions\n- fill: Initial fill — \"transparent\" (default), \"white\", \"black\", or any CSS color\n- opacity: Layer opacity 0-100 (default 100)\n- blend_mode: GIMP layer mode name — \"NORMAL\" (default), \"MULTIPLY\", \"SCREEN\", etc.\n- position: Stack position — -1 = top (default), 0 = bottom\n- image_index: Target image index (default 0)\n\nReturns: {layer_name, layer_id, width, height, position}",
	})
	addObject[AddImageLayerInput](r, toolDef{
		Name:        "add_image_layer",
		Command:     "add_image_layer",
		Required:    []string{"file_path"},
		Description: "Place an image file into the open image as a new layer.\n\nThis is how one image is composited into another: every other command works within a single image, so a logo, photo or texture is brought in here rather than by opening it separately.\n\nParameters:\n- file_path: Absolute path to the image file to place\n- x, y: Top-left corner for the layer (default 0, 0)\n- align: \"left\" (default, uses x), \"center\", or \"right\" (x is the right margin)\n- width, height: Scale the layer to this size; giving one keeps the aspect ratio\n- name: Name for the new layer\n- opacity: Layer opacity 0-100 (default 100)\n- position: Stack position — -1 = top (default), 0 = bottom\n- image_index: Target image index (default 0)\n\nReturns: {status, layer_id, width, height, position}",
	})
	addObject[DuplicateLayerInput](r, toolDef{
		Name:        "duplicate_layer",
		Command:     "duplicate_layer",
		Required:    nil,
		Description: "Duplicate a layer and insert the copy above it.\n\nParameters:\n- layer_name: Name of the layer to duplicate; defaults to active layer\n- image_index: Target image index (default 0)\n\nReturns: {layer_name, layer_id}",
	})
	addObject[DeleteLayerInput](r, toolDef{
		Name:        "delete_layer",
		Command:     "delete_layer",
		Required:    nil,
		Description: "Delete a layer from an image.\n\nParameters:\n- layer_name: Name of the layer to delete\n- layer_index: Position index of the layer (alternative to layer_name)\n- image_index: Target image index (default 0)\n\nProvide either layer_name or layer_index. Defaults to active layer if neither given.\n\nReturns status dict.",
	})
	addObject[RenameLayerInput](r, toolDef{
		Name:        "rename_layer",
		Command:     "rename_layer",
		Required:    []string{"new_name"},
		Description: "Rename a layer.\n\nParameters:\n- new_name: New name for the layer\n- old_name: Current name of the layer to rename\n- layer_index: Position index alternative to old_name\n- image_index: Target image index (default 0)\n\nReturns: {old_name, new_name}",
	})
	addObject[SetLayerPropertiesInput](r, toolDef{
		Name:        "set_layer_properties",
		Command:     "set_layer_properties",
		Required:    nil,
		Description: "Set properties on an existing layer.\n\nParameters:\n- layer_name / layer_index: Identify the layer (defaults to active layer)\n- opacity: New opacity 0-100 (omit to leave unchanged)\n- blend_mode: New GIMP layer mode name (omit to leave unchanged)\n- visible: True/False visibility (omit to leave unchanged)\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[SetLayerOffsetsInput](r, toolDef{
		Name:        "set_layer_offsets",
		Command:     "set_layer_offsets",
		Required:    nil,
		Description: "Move a layer to an exact position on the canvas.\n\nParameters:\n- x, y: New top-left corner of the layer\n- align: \"left\" (default, uses x), \"center\", or \"right\" (x is the right margin)\n- layer_name / layer_index: Identify the layer (defaults to active layer)\n- image_index: Target image index (default 0)\n\nReturns: {status, layer_id, position}",
	})
	addObject[ReorderLayerInput](r, toolDef{
		Name:        "reorder_layer",
		Command:     "reorder_layer",
		Required:    []string{"new_position"},
		Description: "Move a layer to a new stack position.\n\nParameters:\n- new_position: Target stack index (0 = bottom)\n- layer_name / layer_index: Identify the layer (defaults to active layer)\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[FlattenImageInput](r, toolDef{
		Name:        "flatten_image",
		Command:     "flatten_image",
		Required:    nil,
		Description: "Flatten all layers into a single background layer.\n\nParameters:\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[MergeVisibleLayersInput](r, toolDef{
		Name:        "merge_visible_layers",
		Command:     "merge_visible_layers",
		Required:    nil,
		Description: "Merge all visible layers into a single layer.\n\nParameters:\n- image_index: Target image index (default 0)\n\nReturns: {layer_name, layer_id}",
	})
	addObject[ListLayersInput](r, toolDef{
		Name:        "list_layers",
		Command:     "list_layers",
		Required:    nil,
		Description: "List all layers in an image with their properties.\n\nParameters:\n- image_index: Target image index (default 0)\n\nReturns: {layers: [{name, id, visible, opacity, blend_mode, width, height, has_alpha}], count}",
	})
	addObject[FillLayerInput](r, toolDef{
		Name:        "fill_layer",
		Command:     "fill_layer",
		Required:    []string{"color"},
		Description: "Fill an entire layer with a solid color.\n\nParameters:\n- color: Fill color as CSS name, hex, or rgb() string\n- layer_name: Layer to fill; defaults to active layer\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[FillSelectionInput](r, toolDef{
		Name:        "fill_selection",
		Command:     "fill_selection",
		Required:    nil,
		Description: "Fill the current selection with a color or fill type.\n\nParameters:\n- color: Fill color as CSS name, hex, or rgb() string (used when fill_type is omitted)\n- fill_type: Fill type override: \"foreground\", \"background\", or \"transparent\"\n- image_index: Target image index (default 0)\n- layer_name: Target layer; defaults to active layer\n\nReturns status dict.",
	})
	addObject[SetColorsInput](r, toolDef{
		Name:        "set_colors",
		Command:     "set_colors",
		Required:    nil,
		Description: "Set the GIMP foreground and/or background color.\n\nParameters:\n- foreground: New foreground color (CSS name, hex, rgb()); omit to leave unchanged\n- background: New background color; omit to leave unchanged\n\nReturns: {foreground, background} confirmation dict.",
	})
	addObject[DrawLineInput](r, toolDef{
		Name:        "draw_line",
		Command:     "draw_line",
		Required:    []string{"x1", "y1", "x2", "y2"},
		Description: "Draw a straight line on a layer.\n\nParameters:\n- x1, y1: Start point\n- x2, y2: End point\n- color: Stroke color (CSS / hex / rgb); uses current foreground if omitted\n- width: Stroke width in pixels (default 2.0)\n- tool: \"pencil\" (default, hard edge) or \"paintbrush\" (soft edge)\n- layer_name: Target layer; defaults to active layer\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[DrawRectangleInput](r, toolDef{
		Name:        "draw_rectangle",
		Command:     "draw_rectangle",
		Required:    []string{"x", "y", "width", "height"},
		Description: "Draw a rectangle outline (stroke only) on a layer.\n\nParameters:\n- x, y: Top-left corner\n- width, height: Rectangle dimensions\n- color: Stroke color; uses current foreground if omitted\n- line_width: Stroke width in pixels (default 2.0)\n- layer_name: Target layer; defaults to active layer\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[DrawEllipseInput](r, toolDef{
		Name:        "draw_ellipse",
		Command:     "draw_ellipse",
		Required:    []string{"x", "y", "width", "height"},
		Description: "Draw an ellipse outline (stroke only) on a layer.\n\nParameters:\n- x, y: Top-left corner of the bounding box\n- width, height: Bounding box dimensions\n- color: Stroke color; uses current foreground if omitted\n- line_width: Stroke width in pixels (default 2.0)\n- layer_name: Target layer; defaults to active layer\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[FillRectangleInput](r, toolDef{
		Name:        "fill_rectangle",
		Command:     "fill_rectangle",
		Required:    []string{"x", "y", "width", "height", "color"},
		Description: "Fill a rectangular region with a solid color.\n\nParameters:\n- x, y: Top-left corner\n- width, height: Rectangle dimensions\n- color: Fill color (CSS name, hex, or rgb() string)\n- layer_name: Target layer; defaults to active layer\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[FillEllipseInput](r, toolDef{
		Name:        "fill_ellipse",
		Command:     "fill_ellipse",
		Required:    []string{"x", "y", "width", "height", "color"},
		Description: "Fill an elliptical region with a solid color.\n\nParameters:\n- x, y: Top-left corner of the bounding box\n- width, height: Bounding box dimensions\n- color: Fill color (CSS name, hex, or rgb() string)\n- layer_name: Target layer; defaults to active layer\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[GradientFillInput](r, toolDef{
		Name:        "gradient_fill",
		Command:     "gradient_fill",
		Required:    nil,
		Description: "Fill a layer or selection with a gradient.\n\nParameters:\n- color1: Start color (default \"black\")\n- color2: End color (default \"white\")\n- x1, y1: Gradient start point (default top-left 0,0)\n- x2, y2: Gradient end point (defaults to bottom-right of image)\n- gradient_type: \"linear\" (default) or \"radial\"\n- layer_name: Target layer; defaults to active layer\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[AddTextInput](r, toolDef{
		Name:        "add_text",
		Command:     "add_text",
		Required:    []string{"text"},
		Description: "Add a text layer to an image.\n\nParameters:\n- text: The text string to render\n- x, y: Position of the text layer's top-left corner (default 0, 0)\n- font: Font family name — \"Sans\" (default), \"Serif\", etc.\n- size: Font size in pixels (default 24)\n- color: Text color (CSS name, hex, or rgb() string; default \"black\")\n- align: \"left\" (default, places the text at x), \"center\" to centre it on the\n         image, or \"right\" to place it x pixels in from the right edge\n- image_index: Target image index (default 0)\n\nCentring needs the rendered width, so prefer align over measuring the text\nand repositioning the layer yourself.\n\nReturns: {layer_name, layer_id, text_width, text_height, position}",
	})
	addObject[EditTextInput](r, toolDef{
		Name:        "edit_text",
		Command:     "edit_text",
		Required:    []string{"layer_name"},
		Description: "Edit an existing text layer's content or formatting.\n\nParameters:\n- layer_name: Name of the text layer to edit\n- text: New text content (omit to leave unchanged)\n- font: New font family (omit to leave unchanged)\n- size: New font size in pixels (omit to leave unchanged)\n- color: New text color (omit to leave unchanged)\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[ListFontsInput](r, toolDef{
		Name:        "list_fonts",
		Command:     "list_fonts",
		Required:    nil,
		Description: "List available fonts installed in GIMP.\n\nParameters:\n- filter: Optional string to filter font names (case-insensitive substring match)\n\nReturns: {fonts: [font_name, ...], count}",
	})
	addObject[ApplyDropShadowInput](r, toolDef{
		Name:        "apply_drop_shadow",
		Command:     "apply_drop_shadow",
		Required:    nil,
		Description: "Apply a drop shadow effect to a layer.\n\nParameters:\n- offset_x, offset_y: Shadow offset in pixels (default 5, 5)\n- blur_radius: Shadow softness radius (default 10)\n- color: Shadow color (default \"black\")\n- opacity: Shadow opacity 0-100 (default 60)\n- layer_name: Target layer; defaults to active layer\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[ApplyGeglFilterInput](r, toolDef{
		Name:        "apply_gegl_filter",
		Command:     "apply_gegl_filter",
		Required:    []string{"operation"},
		Description: "Run any GEGL operation on a layer.\n\nThe dedicated effect tools cover the common operations; this reaches the rest of GEGL's catalogue, which call_api cannot, because GIMP 3 applies GEGL through libgimp rather than the PDB.\n\nOnly numeric properties can be set. Operations whose properties are colours or enums are not reachable this way, except where the operation samples a colour from the paint context.\n\nParameters:\n- operation: GEGL operation name, e.g. \"gegl:cartoon\", \"gegl:oilify\", \"gegl:posterize\"\n- settings: Numeric properties for the operation, e.g. {\"mask-radius\": 7.0, \"pct-black\": 0.2}\n- layer_name: Target layer; defaults to active layer\n- image_index: Target image index (default 0)\n\nExamples:\n- apply_gegl_filter(operation=\"gegl:cartoon\", settings={\"mask-radius\": 7.0, \"pct-black\": 0.2})\n- apply_gegl_filter(operation=\"gegl:oilify\", settings={\"mask-radius\": 4.0})\n\nReturns status dict.",
	})
	addObject[ApplyGaussianBlurInput](r, toolDef{
		Name:        "apply_gaussian_blur",
		Command:     "apply_gaussian_blur",
		Required:    nil,
		Description: "Apply Gaussian blur as a destructive filter operation.\n\nParameters:\n- radius: Blur radius in pixels (default 5.0)\n- layer_name: Target layer; defaults to active layer\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[ApplyPixelateInput](r, toolDef{
		Name:        "apply_pixelate",
		Command:     "apply_pixelate",
		Required:    nil,
		Description: "Pixelate a layer using a mosaic/block effect.\n\nParameters:\n- block_size: Size of each mosaic block in pixels (default 10)\n- layer_name: Target layer; defaults to active layer\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[ApplyEmbossInput](r, toolDef{
		Name:        "apply_emboss",
		Command:     "apply_emboss",
		Required:    nil,
		Description: "Apply an emboss (bas-relief) effect to a layer.\n\nParameters:\n- azimuth: Light direction in degrees 0-360 (default 315 = top-left)\n- elevation: Light elevation angle 0-90 (default 45)\n- depth: Effect depth/intensity (default 2)\n- layer_name: Target layer; defaults to active layer\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[ApplyVignetteInput](r, toolDef{
		Name:        "apply_vignette",
		Command:     "apply_vignette",
		Required:    nil,
		Description: "Apply a vignette darkening effect around the edges of a layer.\n\nParameters:\n- softness: Edge softness / fade width (default 3.0)\n- shape: Shape factor — 1.0 = elliptical (default), values >1 = more rectangular\n- layer_name: Target layer; defaults to active layer\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[ApplyNoiseInput](r, toolDef{
		Name:        "apply_noise",
		Command:     "apply_noise",
		Required:    nil,
		Description: "Add noise/grain to a layer.\n\nParameters:\n- amount: Noise intensity 0.0-1.0 (default 0.2)\n- layer_name: Target layer; defaults to active layer\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[ExportIconSizesInput](r, toolDef{
		Name:        "export_icon_sizes",
		Command:     "export_icon_sizes",
		Required:    []string{"output_dir"},
		Description: "Export an image as a complete icon set for Android or iOS.\n\nAndroid sizes: 48 (mdpi), 72 (hdpi), 96 (xhdpi), 144 (xxhdpi),\n               192 (xxxhdpi), 512 (Play Store)\niOS sizes: 20x1/2/3, 29x1/2/3, 40x2/3, 60x2/3, 76x1/2, 83.5x2, 1024x1\n\nParameters:\n- output_dir: Directory to write icon files into\n- platform: \"android\" (default) or \"ios\"\n- source_image_index: Image to use as source (default 0)\n- format: Output format — \"png\" (default)\n\nReturns: {exported: [{size, file_path}], count, platform}",
	})
	addObject[ExportWebOptimizedInput](r, toolDef{
		Name:        "export_web_optimized",
		Command:     "export_web_optimized",
		Required:    []string{"output_dir"},
		Description: "Export an image as both JPEG and PNG, choosing the smaller format.\n\nParameters:\n- output_dir: Directory to write output files\n- jpeg_quality: JPEG quality 1-100 (default 85)\n- png_compression: PNG compression level 0-9 (default 9)\n- max_width / max_height: Optional scaling before export\n- image_index: Source image index (default 0)\n\nReturns: {jpeg_path, jpeg_size, png_path, png_size, recommendation}",
	})
	addObject[WarpRegionInput](r, toolDef{
		Name:        "warp_region",
		Command:     "warp_region",
		Required:    []string{"vectors"},
		Description: "Warp / liquify a region of the image by pushing pixels in a direction.\n\nUses GEGL warp (GIMP 3 native) with plug-in-iwarp fallback. Ideal for\nsubtle facial expression edits — e.g. turning a neutral mouth into a smile\nby pushing the mouth corners upward.\n\nParameters:\n- vectors: List of warp stroke dicts, each with:\n    - x, y      : center of the warp influence (pixels)\n    - dx, dy    : push direction — negative dy = push upward\n    - radius    : influence radius in pixels (default: 40)\n    - amount    : deform strength 0–1 (default: 0.3)\n- image_index: Which open image to edit (default: 0)\n- layer_name: Target layer; omit to use the active/top layer\n\nExamples — make a character smile:\n    warp_region(vectors=[\n        {\"x\": 215, \"y\": 355, \"dx\":  5, \"dy\": -8, \"radius\": 18, \"amount\": 0.45},\n        {\"x\": 295, \"y\": 355, \"dx\": -5, \"dy\": -8, \"radius\": 18, \"amount\": 0.45},\n        {\"x\": 255, \"y\": 370, \"dx\":  0, \"dy\": -4, \"radius\": 22, \"amount\": 0.30},\n    ])\n\nReturns: {\"warped_vectors\": N}",
	})
	addObject[BatchResizeInput](r, toolDef{
		Name:        "batch_resize",
		Command:     "batch_resize",
		Required:    nil,
		Description: "Resize all open images to a common target size.\n\nParameters:\n- width / height: Target dimensions in pixels (provide one or both)\n- scale_factor: Proportional scale (e.g. 0.5 = 50%); overrides width/height if set\n- maintain_aspect: Preserve aspect ratio when only one dimension is given (default True)\n\nReturns: {results: [{image_id, old_width, old_height, new_width, new_height}], count}",
	})
	addObject[ExportSpriteSheetInput](r, toolDef{
		Name:        "export_sprite_sheet",
		Command:     "export_sprite_sheet",
		Required:    []string{"output_path"},
		Description: "Combine multiple frames into a sprite sheet PNG.\n\nParameters:\n- output_path: Absolute path for the output PNG file\n- columns: Number of columns in the grid (defaults to square root of frame count)\n- padding: Pixel gap between frames (default 0)\n- source: \"layers\" (each layer is a frame; default) or \"images\" (each open image)\n- image_index: Source image when source=\"layers\" (default 0)\n\nReturns: {file_path, columns, rows, frame_width, frame_height, count}",
	})
	addObject[ExportSocialMediaKitInput](r, toolDef{
		Name:        "export_social_media_kit",
		Command:     "export_social_media_kit",
		Required:    []string{"output_dir"},
		Description: "Export an image resized for multiple social media platforms.\n\nPlatform sizes (all in pixels):\n- instagram_square: 1080x1080\n- instagram_story: 1080x1920\n- twitter_header: 1500x500\n- facebook_cover: 820x312\n- youtube_thumbnail: 1280x720\n\nParameters:\n- output_dir: Directory to write output files\n- platforms: List of platform names to export (omit for all five)\n- image_index: Source image index (default 0)\n\nReturns: {exported: [{platform, file_path, width, height}], count}",
	})
	addObject[ListImagesInput](r, toolDef{
		Name:        "list_images",
		Command:     "list_images",
		Required:    nil,
		Description: "List all images currently open in GIMP.\n\nReturns:\n- images: list of {index, image_id, name, width, height, color_mode,\n                   num_layers, file_path, is_dirty}\n- count: total number of open images",
	})
	addObject[SetActiveImageInput](r, toolDef{
		Name:        "set_active_image",
		Command:     "set_active_image",
		Required:    []string{"image_index"},
		Description: "Raise a specific image to the front / make it active in GIMP.\n\nParameters:\n- image_index: Index of the image to activate (from list_images)\n\nReturns status dict.",
	})
	addObject[UndoInput](r, toolDef{
		Name:        "undo",
		Command:     "undo",
		Required:    nil,
		Description: "Undo one or more operations on an image.\n\nParameters:\n- steps: Number of undo steps (default 1)\n- image_index: Target image index (default 0)\n\nReturns: {steps_undone}\n\nNot available on GIMP 3: the PDB procedures that step the undo stack were removed, so this call always fails. Re-open the image or apply the inverse operation instead.",
	})
	addObject[RedoInput](r, toolDef{
		Name:        "redo",
		Command:     "redo",
		Required:    nil,
		Description: "Redo one or more previously undone operations on an image.\n\nParameters:\n- steps: Number of redo steps (default 1)\n- image_index: Target image index (default 0)\n\nReturns: {steps_redone}\n\nNot available on GIMP 3: the PDB procedures that step the undo stack were removed, so this call always fails. Re-open the image or apply the inverse operation instead.",
	})
	addObject[ConvertColorModeInput](r, toolDef{
		Name:        "convert_color_mode",
		Command:     "convert_color_mode",
		Required:    []string{"mode"},
		Description: "Convert an image to a different color mode.\n\nParameters:\n- mode: \"RGB\", \"GRAY\", or \"INDEXED\"\n- num_colors: Number of colors for INDEXED mode (default 256)\n- image_index: Target image index (default 0)\n\nReturns status dict.",
	})
	addObject[CloseImageInput](r, toolDef{
		Name:        "close_image",
		Command:     "close_image",
		Required:    nil,
		Description: "Close an image, optionally saving as XCF first.\n\nParameters:\n- image_index: Index of the image to close (default 0)\n- save_first: If True, save as XCF before closing (default False)\n- force: If True, close even with unsaved changes, discarding them (default False)\n\nReturns status dict.",
	})
	addObject[GetSelectionBoundsInput](r, toolDef{
		Name:        "get_selection_bounds",
		Command:     "get_selection_bounds",
		Required:    nil,
		Description: "Get the bounding rectangle of the current selection.\n\nParameters:\n- image_index: Target image index (default 0)\n\nReturns: {has_selection, x, y, width, height}",
	})
	addObject[GetPixelColorInput](r, toolDef{
		Name:        "get_pixel_color",
		Command:     "get_pixel_color",
		Required:    []string{"x", "y"},
		Description: "Get the color of a single pixel.\n\nParameters:\n- x, y: Pixel coordinates\n- image_index: Target image index (default 0)\n- layer_name: Layer to sample from; defaults to active layer\n\nReturns: {color_hex, color_rgb: [r, g, b], alpha}",
	})
	addObject[GetHistogramInput](r, toolDef{
		Name:        "get_histogram",
		Command:     "get_histogram",
		Required:    nil,
		Description: "Get histogram statistics for a channel of the active layer.\n\nParameters:\n- channel: \"value\" (all; default), \"red\", \"green\", \"blue\", \"alpha\"\n- image_index: Target image index (default 0)\n\nReturns: {mean, median, std_dev, min, max, pixels, count}",
	})
}

// generatedToolCount is how many tools registerGenerated adds.
const generatedToolCount = 79

// Descriptions for the tools registered by hand in handwritten.go.
const (
	checkServerDesc = "Check whether the GIMP MCP plugin socket is reachable and responding.\n\nReturns a status dict:\n- connected: bool\n- host / port: where it tried\n- gimp_version: if connected successfully\n- error: description if not connected\n\nUse this before any other operation to verify the GIMP plugin is running.\nIf not connected, open GIMP and run Tools > Start MCP Server."

	restartServerDesc = "Drop and re-establish the connection to the GIMP MCP plugin.\n\nUse this when:\n- GIMP was restarted after Claude Code was already running\n- The socket connection dropped mid-session\n- check_server() shows not connected but GIMP is open\n\nReturns the new connection status (same format as check_server)."

	getStateSnapshotDesc = "Return a live visual snapshot of the current image state — no file save needed.\n\nAI agents call this to get immediate visual feedback after any edit operation,\nletting them verify results and decide next steps without saving to disk.\n\nParameters:\n- image_index: Which open image to snapshot (default: 0 = most recent)\n- max_size: Maximum width/height of the returned preview in pixels (default: 512)\n- region: Optional dict {x, y, width, height} to zoom into a specific area\n          e.g. {\"x\": 200, \"y\": 300, \"width\": 100, \"height\": 80} for mouth area\n- label: Optional annotation label (logged but not drawn — for agent bookkeeping)\n\nReturns:\n- PNG image of the current GIMP canvas state (with alpha if present)\n\nTypical agent workflow:\n    1. open_image / new_canvas\n    2. <edit operations>\n    3. get_state_snapshot()          ← see result, decide next step\n    4. <more edits>\n    5. get_state_snapshot(region={\"x\":200,\"y\":300,\"width\":100,\"height\":80})\n    6. export_image when satisfied"

	callAPIDesc = "Run a GIMP procedure from the Procedural Database (PDB).\n\nThis is the escape hatch for anything the dedicated tools do not cover. It\nnames a procedure and passes its arguments; it does NOT execute source code.\n\nThe plug-in is built against libgimp, so there is no interpreter inside GIMP\nto evaluate snippets. Anything you would write in GIMP's Python-Fu console is\nexpressed as the procedure it calls:\n\n    Python-Fu                      call_api\n    Gimp.get_images()              api_path=\"gimp-get-images\"\n    image.get_layers()             api_path=\"gimp-image-get-layers\",\n                                   kwargs={\"image\": 1}\n    Gimp.displays_flush()          api_path=\"gimp-displays-flush\"\n\nParameters:\n- api_path: The PDB procedure name, e.g. \"gimp-image-get-layers\". GIMP spells\n            these with dashes.\n- args: Positional arguments, matched in order against the procedure's\n        declared arguments.\n- kwargs: Arguments by name. Preferred, and required when skipping any.\n\nArgument values:\n- Images, layers, drawables, channels and fonts are passed as integer ids,\n  the same ids the other tools return.\n- Colors are CSS strings: \"white\", \"#ff5733\", \"rgb(100,200,50)\".\n- Coordinate lists are flat arrays of numbers.\n- Pass -1 for an object argument that should be NULL, such as a layer's\n  parent.\n\nCall describe_procedure first when you do not know a procedure's exact\nargument names; GIMP rejects unknown names rather than ignoring them.\n\nReturns:\n- JSON with the procedure name and its return values. Object results are\n  returned as integer ids.\n\nFull procedure reference: https://developer.gimp.org/api/3.0/libgimp/"
)
